# These are supported funding model platforms
# github: [rajamohan1950]
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# custom: ['https://alphaforge.ai'] # Replace with up to 4 custom sponsorship URLs
