"""Pay-as-you-go pricing for metered events (ADR 0001 step 2.5).

Rule: the flat monthly tier fee covers every operation up to
`TIER_LIMITS[tier]["ops_per_month"]`. Once that cap is crossed,
each additional operation is priced at the per-tier, per-event-type
rate defined in `settings.overage_rates_cents`.

Defaults are **zero** so flipping the pricer on without configuring
rates is a safe no-op — it cannot accidentally bill someone. Rates
become non-zero only when `CLS_OVERAGE_RATES_CENTS` is set
explicitly by the owner on Render.
"""

from __future__ import annotations

import logging
import time
from typing import Optional

from clsplusplus.config import Settings
from clsplusplus.tiers import TIER_LIMITS, Tier

logger = logging.getLogger(__name__)

# Default rate table: every tier, every event, zero cents.
# Overridden by settings.overage_rates_cents (which is JSON-loaded env).
_ZERO_RATES: dict[str, dict[str, int]] = {
    t.value: {"_default": 0} for t in Tier
}


def compute_unit_cost_cents(
    tier: str,
    event_type: str,
    current_ops: int,
    cap: int,
    rates: Optional[dict[str, dict[str, int]]] = None,
) -> int:
    """Pure function. Given the raw inputs, return the cost for ONE event.

    `current_ops` is the actor's operation count for the current period
    *including* this event (so the caller increments before calling).

    `cap` is the tier's flat-tier ops ceiling. A non-positive value means
    unlimited (enterprise) — always 0.

    `rates` is a nested dict `{tier_name: {event_type: cents, "_default": cents}}`.
    An unknown tier or event_type falls through to 0.
    """
    if cap <= 0:
        return 0
    if current_ops <= cap:
        return 0
    table = (rates or _ZERO_RATES).get(tier, {})
    return int(table.get(event_type, table.get("_default", 0)))


class MeteringPricer:
    """Stamps unit_cost_cents at write time.

    Owns a small in-memory LRU of `api_key_hash → tier` with a TTL so
    the hot path doesn't hit the DB on every request. The cache is
    flushed on every tier change via `invalidate()`.
    """

    def __init__(
        self,
        settings: Settings,
        integration_store,
        get_ops_counter,
        cache_ttl_seconds: int = 300,
    ):
        self.settings = settings
        self._integration_store = integration_store
        self._get_ops = get_ops_counter
        self._ttl = cache_ttl_seconds
        self._tier_cache: dict[str, tuple[str, float]] = {}

    def invalidate(self, api_key: Optional[str] = None) -> None:
        """Drop the cache. Call when a user's tier changes."""
        if api_key is None:
            self._tier_cache.clear()
        else:
            self._tier_cache.pop(api_key, None)

    async def price_event(self, api_key: Optional[str], event_type: str) -> int:
        """Return the cost in cents for an event generated by `api_key`.

        `event_type` is the operation name (write/read/etc.). Non-api_key
        actors (anonymous, user-cookie-only) return 0 because they are
        not priced — API-key usage is the only billable surface today.
        """
        if not api_key:
            return 0
        tier = await self._resolve_tier(api_key)
        if not tier:
            return 0
        try:
            tier_enum = Tier(tier)
        except ValueError:
            logger.warning("pricer: unknown tier %r, treating as free", tier)
            return 0
        cap = TIER_LIMITS[tier_enum]["ops_per_month"]
        current = await self._get_ops(api_key, self.settings)
        return compute_unit_cost_cents(
            tier, event_type, current, cap, self.settings.overage_rates_cents,
        )

    async def _resolve_tier(self, api_key: str) -> Optional[str]:
        now = time.monotonic()
        cached = self._tier_cache.get(api_key)
        if cached and cached[1] > now:
            return cached[0]
        try:
            tier = await self._integration_store.resolve_tier_from_key(api_key)
        except Exception as exc:
            logger.warning("pricer: tier resolution failed: %s: %s",
                           type(exc).__name__, exc)
            return None
        if tier:
            self._tier_cache[api_key] = (tier, now + self._ttl)
        return tier
